chore: remove dependence on poetry shell in direnv

diff --git a/direnv/.config/direnv/direnvrc b/direnv/.config/direnv/direnvrc
--- a/direnv/.config/direnv/direnvrc
+++ b/direnv/.config/direnv/direnvrc
@@ -26,9 +26,13 @@
 #     export VIRTUAL_ENV
 # }
 # Ref: https://github.com/direnv/direnv/issues/592#issuecomment-2253281720
+# layout_poetry() {
+#     if ! direnv_load poetry run direnv dump; then
+#       log_error "failed to enter Poetry env, do you need 'poetry install'?"
+#       return 2
+#     fi
+# }
+
 layout_poetry() {
-    if ! direnv_load poetry run direnv dump; then
-      log_error "failed to enter Poetry env, do you need 'poetry install'?"
-      return 2
-    fi
+	eval $(poetry env activate)
 }
